# Generated by Django 4.2.6 on 2023-10-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(),
        ),
    ]
