# Generated by Django 4.2.6 on 2023-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_cliente_estatura_alter_cliente_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imc',
            field=models.FloatField(),
        ),
    ]
